kind: Secret
apiVersion: v1
metadata:
  name: mongo-secret
  namespace: three-tier
type: Opaque
stringData: 
   MONGO_INITDB_ROOT_USERNAME: "admin"
   MONGO_INITDB_ROOT_PASSWORD: "supersecretpassword123"
   MONGO_CONN_STR: "mongodb://admin:supersecretpassword123@mongodb-service:27017/taskdb?authSource=admin"
