kind: Deployment
apiVersion: apps/v1
metadata:
   name: frontend-deployment
   namespace: three-tier
spec:
  replicas: 1
  selector:
   matchLabels:
    app: frontend
  template:
   metadata:
    labels:
      app: frontend

   spec:
     containers:
       - name: frontend
         image: mandhar12/three-tier-frontend:1.0
         ports:
          - containerPort: 3000
         env:
           - name: REACT_APP_BACKEND_URL
             value: "http://3.133.14.133:8080/api/tasks"
