kind: Deployment
apiVersion: apps/v1
metadata:
   name: frontend-deployment
   namespace: three-tier
spec:
  replicas: 1
  selector:
   matchLabels:
    app: frontend
  template:
   metadata:
    labels:
      app: frontend

   spec:
     affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - frontend
     containers:
       - name: frontend
         image: mandhar12/three-tier-frontend:1.0
         ports:
          - containerPort: 3000
         env:
           - name: REACT_APP_BACKEND_URL
             value: "http://a68b0309d7cf54e1f8f1b89ed092638e-1088066927.us-east-2.elb.amazonaws.com:3500/api/tasks"
